### ISSUE TITLE
Unexplained panic at random times when using copy_image_to_buffer

### ISSUE THREAD

**Issue by Raz-Hemo** [vulkano-rs/vulkano#1336] opened 2020-03-30 14:48 UTC
Version of vulkano: 0.18.0
OS: Windows 10 version 1903
GPU (the selected PhysicalDevice): NVidia GTX 1060
GPU Driver: 445.75

I'm writing picking logic that writes an image of u32 in the fragment shader, as well as the regular color output. In order to access this information, a copy is needed to transfer this image into a CpuAccessibleBuffer<u32> which i then read. The reads themselves are successful and correct, but some time after the program starts (whether 1 frame, 10 frames or even several minutes into it), a panic without any indicative message happens:

`A panic occurred at <::std::macros::panic_macros>:5: assertion failed: (left == right)`

The call stack shows that this happens inside the copy_image_to_buffer function, which is called like this:
```
command_buffer = command_buffer
            .end_render_pass().expect("Failed to end render pass")
            .copy_image_to_buffer(
                self.picking_buffers[image_num].clone(),
                self.picking_outputs.last().unwrap().clone(),
            ).expect("Failed to add copy pickbuf command");
let future = vulkano::sync::now(self.device.clone())
            .join(acquire_future)
            .then_execute(
                self.queue.clone(), command_buffer.build().expect("Failed to build command buffer"))
            .expect("Failed to add command buffer")
            .then_swapchain_present(self.queue.clone(), self.swapchain.clone(), image_num)
```

The buffers and images are created like this:
```
CpuAccessibleBuffer::from_iter(
            self.device.clone(),
            BufferUsage::all(),
            true,
            (0 .. self.resolution[0] * self.resolution[1]).map(|_| std::u32::MAX))
        .expect("Failed to create pick output buffer")

AttachmentImage::with_usage(
                device.clone(), dims, Format::R32Uint,
                ImageUsage {storage: true, transfer_source: true, ..ImageUsage::none()}
                ).expect("Failed to create picking image")
```

I also have the standard debugging validation layers output here: [validation.txt](https://github.com/vulkano-rs/vulkano/files/4403739/validation.txt)

I've also tried using a compute shader to copy the images, but ran into a similar problem (only instead of this randomly occurring panic, i got another randomly occurring panic inside the command buffer `build()` method).
Am I missing something here? I'd love to hear if there is another way to copy this information that I can try and use to circumvent this.

Thanks!

**Comment by Raz-Hemo** [comment] 2020-04-02 14:15
Update: Lookin at vulkano's code, this seems to happen in `command_buffer/base/synced/base.rs`, specifically in line 950. As far as I can tell the buffer and image are conflicting sometimes, but beyond that I don't really understand the inner workings.

This is the problematic call stack:
```
...
// Panic happens above this stack
myprogram.exe!vulkano::command_buffer::synced::commands::{{impl}}::copy_image_to_buffer::{{impl}}::into_final_command::{{impl}}::image<alloc::sync::Arc<vulkano::image::attachment::AttachmentImage<vulkano::format::Format, vulkano::memory::pool::PotentialDedicatedAllocation<vulkano::memory::pool::pool::StdMemoryPoolAlloc>>>,alloc::sync::Arc<vulkano::buffer::cpu_access::CpuAccessibleBuffer<slice<u32>, vulkano::memory::pool::PotentialDedicatedAllocation<vulkano::memory::pool::pool::StdMemoryPoolAlloc>>>>(vulkano::command_buffer::synced::commands::{{impl}}::copy_image_to_buffer::{{impl}}::into_final_command::Fin<alloc::sync::Arc<vulkano::image::attachment::AttachmentImage<vulkano::format::Format, vulkano::memory::pool::PotentialDedicatedAllocation<vulkano::memory::pool::pool::StdMemoryPoolAlloc>>>, alloc::sync::Arc<vulkano::buffer::cpu_access::CpuAccessibleBuffer<slice<u32>, vulkano::memory::pool::PotentialDedicatedAllocation<vulkano::memory::pool::pool::StdMemoryPoolAlloc>>>> * self, unsigned __int64 num) Line 5 (<::std::macros::panic macros>:5)
myprogram.exe!vulkano::command_buffer::synced::base::{{impl}}::conflicts_image::{{closure}}(vulkano::command_buffer::synced::base::{{impl}}::conflicts_image::closure-2 * command_id, unsigned __int64 *) Line 990 (c:\Users\Raz\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\command_buffer\synced\base.rs:990)
myprogram.exe!core::iter::traits::iterator::Iterator::any::check::{{closure}}<usize*,closure-2>(core::iter::traits::iterator::Iterator::any::check::closure-0 *, ..., unsigned __int64 * x) Line 2006 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:2006)
myprogram.exe!core::iter::traits::iterator::Iterator::try_fold<core::slice::Iter<usize>,(),closure-0,core::iter::LoopState<(), ()>>(core::slice::Iter<usize> * self, ..., core::iter::traits::iterator::Iterator::any::check::closure-0 f) Line 1776 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:1776)
myprogram.exe!core::iter::traits::iterator::Iterator::any<core::slice::Iter<usize>,closure-2>(core::slice::Iter<usize> * self, vulkano::command_buffer::synced::base::{{impl}}::conflicts_image::closure-2 f) Line 2010 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:2010)
myprogram.exe!vulkano::command_buffer::synced::base::CbKey::conflicts_image(core::option::Option<alloc::vec::Vec<alloc::boxed::Box<FinalCommand>>*> self, vulkano::image::traits::ImageAccess* commands_lock) Line 988 (c:\Users\Raz\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\command_buffer\synced\base.rs:988)
myprogram.exe!vulkano::command_buffer::synced::base::{{impl}}::eq::{{closure}}(vulkano::command_buffer::synced::base::{{impl}}::eq::closure-1 * command_id, unsigned __int64 *) Line 1030 (c:\Users\Raz\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\command_buffer\synced\base.rs:1030)
myprogram.exe!core::iter::traits::iterator::Iterator::any::check::{{closure}}<usize*,closure-1>(core::iter::traits::iterator::Iterator::any::check::closure-0 *, ..., unsigned __int64 * x) Line 2006 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:2006)
myprogram.exe!core::iter::traits::iterator::Iterator::try_fold<core::slice::Iter<usize>,(),closure-0,core::iter::LoopState<(), ()>>(core::slice::Iter<usize> * self, ..., core::iter::traits::iterator::Iterator::any::check::closure-0 f) Line 1776 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:1776)
myprogram.exe!core::iter::traits::iterator::Iterator::any<core::slice::Iter<usize>,closure-1>(core::slice::Iter<usize> * self, vulkano::command_buffer::synced::base::{{impl}}::eq::closure-1 f) Line 2010 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:2010)
myprogram.exe!vulkano::command_buffer::synced::base::{{impl}}::eq(vulkano::command_buffer::synced::base::CbKey * self, vulkano::command_buffer::synced::base::CbKey * other) Line 1028 (c:\Users\Raz\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\command_buffer\synced\base.rs:1028)
myprogram.exe!hashbrown::map::{{impl}}::insert::{{closure}}<vulkano::command_buffer::synced::base::CbKey,vulkano::command_buffer::synced::base::ResourceFinalState,core::hash::BuildHasherDefault<fnv::FnvHasher>>(hashbrown::map::{{impl}}::insert::closure-0 * x, (vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState) *) Line 851 (c:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.6.2\src\map.rs:851)
myprogram.exe!hashbrown::raw::RawTable<(vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState)>::find<(vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState),closure-0>(unsigned __int64 self, hashbrown::map::{{impl}}::insert::closure-0 hash) Line 887 (c:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.6.2\src\raw\mod.rs:887)
myprogram.exe!hashbrown::map::HashMap<vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState, core::hash::BuildHasherDefault<fnv::FnvHasher>>::insert<vulkano::command_buffer::synced::base::CbKey,vulkano::command_buffer::synced::base::ResourceFinalState,core::hash::BuildHasherDefault<fnv::FnvHasher>>(vulkano::command_buffer::synced::base::CbKey self, vulkano::command_buffer::synced::base::ResourceFinalState k) Line 851 (c:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.6.2\src\map.rs:851)
myprogram.exe!hashbrown::map::{{impl}}::extend::{{closure}}<vulkano::command_buffer::synced::base::CbKey,vulkano::command_buffer::synced::base::ResourceFinalState,core::hash::BuildHasherDefault<fnv::FnvHasher>,core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0>>(hashbrown::map::{{impl}}::extend::closure-0 *, (vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState)) Line 2579 (c:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.6.2\src\map.rs:2579)
myprogram.exe!core::iter::traits::iterator::Iterator::for_each::call::{{closure}}<(vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState),closure-0>(core::iter::traits::iterator::Iterator::for_each::call::closure-0 *, ..., (vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState) item) Line 652 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:652)
myprogram.exe!core::iter::adapters::map_fold::{{closure}}<(vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState),(vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState),(),closure-0,closure-0>(core::iter::adapters::map_fold::closure-0 * elt, ..., (vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState)) Line 772 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\adapters\mod.rs:772)
myprogram.exe!core::iter::traits::iterator::Iterator::fold::ok::{{closure}}<(),(vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState),closure-0>(core::iter::traits::iterator::Iterator::fold::ok::closure-0 * acc, ..., (vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState) x) Line 1900 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:1900)
myprogram.exe!core::iter::traits::iterator::Iterator::try_fold<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>,(),closure-0,core::result::Result<(), !>>(std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState> * self, ..., core::iter::traits::iterator::Iterator::fold::ok::closure-0 f) Line 1776 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:1776)
myprogram.exe!core::iter::traits::iterator::Iterator::fold<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>,(),closure-0>(std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState> self, ..., core::iter::adapters::map_fold::closure-0 f) Line 1903 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:1903)
myprogram.exe!core::iter::adapters::{{impl}}::fold<(vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState),std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>,closure-0,(),closure-0>(core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0> self, ..., core::iter::traits::iterator::Iterator::for_each::call::closure-0 g) Line 812 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\adapters\mod.rs:812)
myprogram.exe!core::iter::traits::iterator::Iterator::for_each<core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0>,closure-0>(core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0> self, hashbrown::map::{{impl}}::extend::closure-0 f) Line 655 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:655)
myprogram.exe!hashbrown::map::{{impl}}::extend<vulkano::command_buffer::synced::base::CbKey,vulkano::command_buffer::synced::base::ResourceFinalState,core::hash::BuildHasherDefault<fnv::FnvHasher>,core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0>>(hashbrown::map::HashMap<vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState, core::hash::BuildHasherDefault<fnv::FnvHasher>> * self, core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0> iter) Line 2578 (c:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\hashbrown-0.6.2\src\map.rs:2578)
myprogram.exe!std::collections::hash::map::{{impl}}::extend<vulkano::command_buffer::synced::base::CbKey,vulkano::command_buffer::synced::base::ResourceFinalState,core::hash::BuildHasherDefault<fnv::FnvHasher>,core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0>>(std::collections::hash::map::HashMap<vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState, core::hash::BuildHasherDefault<fnv::FnvHasher>> * self, core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0> iter) Line 2391 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\collections\hash\map.rs:2391)
myprogram.exe!std::collections::hash::map::{{impl}}::from_iter<vulkano::command_buffer::synced::base::CbKey,vulkano::command_buffer::synced::base::ResourceFinalState,core::hash::BuildHasherDefault<fnv::FnvHasher>,core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0>>(core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0> iter) Line 2375 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libstd\collections\hash\map.rs:2375)
myprogram.exe!core::iter::traits::iterator::Iterator::collect<core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0>,std::collections::hash::map::HashMap<vulkano::command_buffer::synced::base::CbKey, vulkano::command_buffer::synced::base::ResourceFinalState, core::hash::BuildHasherDefault<fnv::FnvHasher>>>(core::iter::adapters::Map<std::collections::hash::map::IntoIter<vulkano::command_buffer::synced::base::BuilderKey<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>, vulkano::command_buffer::synced::base::ResourceState>, closure-0> self) Line 1559 (c:\rustc\b8cedc00407a4c56a3bda1ed605c6fc166655447\src\libcore\iter\traits\iterator.rs:1559)
myprogram.exe!vulkano::command_buffer::synced::base::SyncCommandBufferBuilder<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>::build<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>(vulkano::command_buffer::synced::base::SyncCommandBufferBuilder<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder> self) Line 788 (c:\Users\Raz\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\command_buffer\synced\base.rs:788)
myprogram.exe!vulkano::command_buffer::auto::AutoCommandBufferBuilder<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>::build<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder>(vulkano::command_buffer::auto::AutoCommandBufferBuilder<vulkano::command_buffer::pool::standard::StandardCommandPoolBuilder> self) Line 473 (c:\Users\Raz\.cargo\registry\src\github.com-1ecc6299db9ec823\vulkano-0.18.0\src\command_buffer\auto.rs:473)
myprogram.exe!myprogram::engine::graphics::renderer::Renderer::draw_frame(alloc::vec::Vec<(myprogram::engine::graphics::models::ModelID, alloc::sync::Arc<vulkano::buffer::immutable::ImmutableBuffer<slice<myprogram::engine::systems::static_mesh::MeshInstance>, vulkano::memory::pool::PotentialDedicatedAllocation<vulkano::memory::pool::pool::StdMemoryPoolAlloc>>>)> * self, cgmath::matrix::Matrix4<f32> meshes, unsigned int[2] view) Line 352 (c:\Users\Raz\Documents\source dump\myprogram\src\engine\graphics\renderer.rs:352)
myprogram.exe!myprogram::engine::Engine::renderer_draw_frame(myprogram::engine::camera::Camera * self) Line 72 (c:\Users\Raz\Documents\source dump\myprogram\src\engine\mod.rs:72)
myprogram.exe!myprogram::engine::Engine::draw_frame() Line 92 (c:\Users\Raz\Documents\source dump\myprogram\src\engine\mod.rs:92)
```

**Comment by AustinJ235** [comment] 2020-04-19 19:04
Check to make sure all your formats are matching.

**Comment by SamHSmith** [comment] 2020-05-11 15:13
I can confirm I have this issue to. Although the weirdest part is that I just rerun it and eventually it goes away for a while.

**Comment by Rua** [comment] 2022-12-28 18:17
The relevant code has changed so much since this issue was reported, it's likely that it's not a problem anymore. I'll close it, please reopen if it's still there.

**Closed by Rua** 2022-12-28 18:17 UTC
Labels: status: unknown-cause
