### ISSUE TITLE
vulkano-shaders: shader! behavior differs between using bytes and path field

### ISSUE THREAD

**Issue by adrianisuru** [vulkano-rs/vulkano#1475] opened 2021-01-15 01:27 UTC
*   Version of vulkano: 0.20.0
*   Version of vulkano-shaders: 0.20.0
*   OS: manjaro (Kernel: 5.9.16-1-MANJARO)
*   GPU (the selected PhysicalDevice): AMD ATI Radeon HD 7770/8760 / R7 250X
*   GPU Driver: radeon, amdgpu

Project structure:
```
$ tree
.
├── Cargo.toml
├── src
   ├── cs.glsl
   └── lib.rs
```
Relevant files:
```rust
// src/lib.rs
mod cs {
    vulkano_shaders::shader! {
        ty: "compute",
        bytes: "src/cs.spv"
    }
}
```
```glsl
// src/cs.glsl
// Shader taken from https://github.com/vulkano-rs/vulkano-www/blob/master/examples/guide-compute-operations.rs
#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Data {
    uint data[];
} buf;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    buf.data[idx] *= 12;
}
```
```toml
# Cargo.toml
[package]
name = "vulkano-shaders-error"
version = "0.1.0"
authors = ["adrianisuru"]
edition = "2018"

[dependencies]
vulkano = "0.20.0"
vulkano-shaders = "0.20.0"
```

# Issue
First I compile `cs.glsl` with `glslangValidator`. This produces `src/cs.spv`. Here is the output (with version info):
```
$ glslangValidator -V -v -S comp -o src/cs.spv src/cs.glsl
Glslang Version: 10:11.0.0
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 11.0.0
GLSL Version: 4.60 glslang Khronos. 11.0.0
SPIR-V Version 0x00010500, Revision 3
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 10
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100
src/cs.glsl

$ tree
.
├── Cargo.toml
├── src
   ├── cs.glsl
   ├── cs.spv
   └── lib.rs
```

Next I compile with `cargo` which prints the error message:
```
$ cargo build
   Compiling vulkano-shaders-error v0.1.0 (/home/adrianisuru/IdeaProjects/vulkano-shaders-error)
error: proc macro panicked
 --> src/lib.rs:2:5
  |
2 | /     vulkano_shaders::shader! {
3 | |         ty: "compute",
4 | |         bytes: "src/cs.spv"
5 | |     }
  | |_____^
  |
  = help: message: Structs in shader interface are expected to be decorated with Block

error: aborting due to previous error

error: could not compile `vulkano-shaders-error`

To learn more, run the command again with --verbose.
```

I believe the help message is talking about `BufferBlock` seen in the output of `glslangValidator -H` below:
```
$ glslangValidator -H -S comp -o src/cs.spv src/cs.glsl
src/cs.glsl
// Module Version 10000
// Generated by (magic number): 8000a
// Id's are bound by 32

                              Capability Shader
               1:             ExtInstImport  "GLSL.std.450"
                              MemoryModel Logical GLSL450
                              EntryPoint GLCompute 4  "main" 11
                              ExecutionMode 4 LocalSize 64 1 1
                              Source GLSL 450
                              Name 4  "main"
                              Name 8  "idx"
                              Name 11  "gl_GlobalInvocationID"
                              Name 17  "Data"
                              MemberName 17(Data) 0  "data"
                              Name 19  "buf"
                              Decorate 11(gl_GlobalInvocationID) BuiltIn GlobalInvocationId
                              Decorate 16 ArrayStride 4
                              MemberDecorate 17(Data) 0 Offset 0
                              Decorate 17(Data) BufferBlock
                              Decorate 19(buf) DescriptorSet 0
                              Decorate 19(buf) Binding 0
                              Decorate 31 BuiltIn WorkgroupSize
               2:             TypeVoid
               3:             TypeFunction 2
               6:             TypeInt 32 0
               7:             TypePointer Function 6(int)
               9:             TypeVector 6(int) 3
              10:             TypePointer Input 9(ivec3)
11(gl_GlobalInvocationID):     10(ptr) Variable Input
              12:      6(int) Constant 0
              13:             TypePointer Input 6(int)
              16:             TypeRuntimeArray 6(int)
        17(Data):             TypeStruct 16
              18:             TypePointer Uniform 17(Data)
         19(buf):     18(ptr) Variable Uniform
              20:             TypeInt 32 1
              21:     20(int) Constant 0
              23:      6(int) Constant 12
              24:             TypePointer Uniform 6(int)
              29:      6(int) Constant 64
              30:      6(int) Constant 1
              31:    9(ivec3) ConstantComposite 29 30 30
         4(main):           2 Function None 3
               5:             Label
          8(idx):      7(ptr) Variable Function
              14:     13(ptr) AccessChain 11(gl_GlobalInvocationID) 12
              15:      6(int) Load 14
                              Store 8(idx) 15
              22:      6(int) Load 8(idx)
              25:     24(ptr) AccessChain 19(buf) 21 22
              26:      6(int) Load 25
              27:      6(int) IMul 26 23
              28:     24(ptr) AccessChain 19(buf) 21 22
                              Store 28 27
                              Return
                              FunctionEnd

```

I don't know why it compiles fine when I use the `path` field of `shader!`. The version of `lib.rs` below compiles fine.
```rust
// src/lib.rs
mod cs {
    vulkano_shaders::shader! {
        ty: "compute",
        path: "src/cs.glsl"
    }
}
```

**Comment by Eliah-Lakhin** [comment] 2021-01-15 06:06
@adrianisuru Think for reporting the issue. Vulkano Shaders subproject uses shaderc under the hood for the shader compilation into sprv bytecode. It would be curious to see the distinction between shaderc-rs output and the sprv output from your example.

The compilation entry-point is here: https://github.com/vulkano-rs/vulkano/blob/master/vulkano-shaders/src/lib.rs#L608 Would you mind to dig a little deeper to find a root cause, please?

**Comment by adrianisuru** [comment] 2021-01-18 01:22
I updated rustup and I'm not getting the error anymore.

**Comment by Eliah-Lakhin** [comment] 2021-01-18 01:32
ok, I'm closing the issue then.

**Closed by Eliah-Lakhin** 2021-01-18 01:32 UTC
