### ISSUE TITLE
Validation error for gl-interop example

### ISSUE THREAD

**Issue by Rua** [vulkano-rs/vulkano#1764] opened 2021-11-24 14:42 UTC
@fayalalebrun I get this error:

> VUID-vkBindBufferMemory-bufferDeviceAddress-03339(ERROR / SPEC): msgNum: 1151829889 - Validation Error: [ VUID-vkBindBufferMemory-bufferDeviceAddress-03339 ] Object 0: handle = 0xcb3ee80000000007, type = VK_OBJECT_TYPE_BUFFER; | MessageID = 0x44a78781 | vkBindBufferMemory(): If buffer was created with the VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT bit set, memory must have been allocated with the VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT bit set. The Vulkan spec states: If the VkPhysicalDeviceBufferDeviceAddressFeatures::bufferDeviceAddress feature is enabled and buffer was created with the VK_BUFFER_USAGE_SHADER_DEVICE_ADDRESS_BIT bit set, memory must have been allocated with the VK_MEMORY_ALLOCATE_DEVICE_ADDRESS_BIT bit set (https://vulkan.lunarg.com/doc/view/1.2.198.0/linux/1.2-extensions/vkspec.html#VUID-vkBindBufferMemory-bufferDeviceAddress-03339)

This may be an oversight or a missing feature.

Also a bug, but possibly unrelated: The example doesn't close when I click the X on the window, although the rendered image still changes so it's not frozen.

**Comment by Eliah-Lakhin** [comment] 2021-11-24 15:34
@fayalalebrun Can you take a look, please? This is related to the example we added recently in #1734

**Comment by fayalalebrun** [comment] 2021-11-24 18:25
I can confirm I can reproduce this issue. I think since the error is related to a buffer memory allocation, it's probably unrelated to the image export functionality, and is triggered by vertex buffer creation (The only buffer used in the example). Probably there's an error in the memory builder similar to the one I fixed for exported memory/dedicated memory. I'll look into it.

I think the example not closing is unrelated. I'll look into that as well.

**Closed** 2021-12-05 21:12 UTC
