### ISSUE TITLE
Apple M1 assertion on limits().max_uniform_buffer_range()

### ISSUE THREAD

**Issue by seratonik** [vulkano-rs/vulkano#1495] opened 2021-02-15 21:56 UTC
*   Version of vulkano: 0.20.0
*   OS: macOS Big Sur (11.2.1)
*   GPU (the selected PhysicalDevice): Apple M1
*   GPU Driver: Unknown
*   Vulkan SDK Version: 1.2.162.1 (Jan 12, 2021)

# Issue

Upon initialization, this command will fail:

```rust
let caps = surface.capabilities(physical).unwrap();
```

The error is related to an unwrap on a None value from this line in `swapchain/surface.rs` in Vulkano (~Line 640):

```rust
Format::from_vulkan_num(f.format).unwrap(),
```

Upon investigation, `f.format` is equal to `0` in this situation.

If I override and filter for f.format > 0 before running the map it will successfully initialize, however another problem arises in the form of:

```
thread 'main' panicked at 'assertion failed: size <=\n    buffer.device().physical_device().limits().max_uniform_buffer_range() as\n        usize', .../vulkano-0.20.0/src/descriptor/descriptor_set/sys.rs:938:9
```

Where `max_uniform_buffer_range()` is equal to `0` when debugging. Other device limits seem to be correct, such as max color attachments, framebuffer dimensions, etc.

**Comment by Eliah-Lakhin** [comment] 2021-02-17 14:19
@seratonik Is it tested from the latest master? We recently merged a PR that pulls additional Device feature required in particular for some Apple environments: https://github.com/vulkano-rs/vulkano/pull/1489

**Comment by seratonik** [comment] 2021-02-17 18:54
@Eliah-Lakhin After changing from the 0.20.0 from crates.io to the master branch from here on Github, it got me past the first issue of not matching the format properly. However the second issue remains:

```
thread 'main' panicked at 'assertion failed: size <=\n    buffer.device().physical_device().limits().max_uniform_buffer_range() as\n        usize', /Users/brent/.cargo/git/checkouts/vulkano-cb672043253a6e8d/e66e9a1/vulkano/src/descriptor/descriptor_set/sys.rs:943:9
```

Thanks for the suggestion of using master though, it got me a little further along at least!

**Comment by Eliah-Lakhin** [comment] 2021-02-18 23:07
@seratonik The second issue is probably some internal case we don't cover properly. It's hard to determine the issue and possible workaround without seeing the entire MVP code(I also don't have Mac to debug it). But probably this is Vulkano bug.

I would be very appreciated if you try to debug it on your machine and maybe prepare a PR with the fix.

**Comment by seratonik** [comment] 2021-02-19 01:05
@Eliah-Lakhin I don't have a deep understanding of the ecosystem around Vulkan/Vulkano, but I'll see if I can dig deeper and will report back with any findings. Thanks for your time!

**Comment by jiegec** [comment] 2021-02-21 08:15
I got the same error in Apple M1 with version 0.20.0, and the error disappear when I use the code from git master branch.

**Comment by seratonik** [comment] 2021-02-23 00:54
@Eliah-Lakhin Following up, I discovered that the `vulkaninfo` utility that comes with the Vulkan SDK reports the following:

```
	maxUniformBufferRange                           = 0
	maxStorageBufferRange                           = 0
```

If I remove the bounds check assertion in Vulkano everything runs fine - so I believe the problem is upstream and is just being mis-reported.

**Comment by jiegec** [comment] 2021-02-25 10:56
It is fixed in MoltenVK master: https://github.com/KhronosGroup/MoltenVK/issues/1240

**Comment by jiegec** [comment] 2021-03-02 15:19
Upgraded to Vulkan sdk 1.2.170.0 and the problem is gone.

**Closed** 2022-08-12 13:09 UTC
Labels: type: bug, help wanted, status: needs investigation
