### ISSUE TITLE
Segfault when creating a buffer with exportable fd on Linux after updating to 0.22

### ISSUE THREAD

**Issue by hakolao** [vulkano-rs/vulkano#1545] opened 2021-04-09 13:57 UTC
After updating to 0.22 I get segfault when creating a `DeviceLocalBuffer::raw_with_exportable_fd`.

*   Version of vulkano: 0.22
*   OS: Linux
*   GPU (the selected PhysicalDevice): GeForce RTX 2070 with Max-Q Design with 7.5 CUDA compute capability
*   GPU Driver: `460.32.03`
*   Upload of a reasonably minimal complete `main.rs` file that demonstrates the issue: TODO

# Issue

Segfault after #1510. Segfaulting at:
`ptr_chain_iter`
![image](https://user-images.githubusercontent.com/12234005/114188581-f5ca2b00-9951-11eb-90d8-77e465a7d943.png)

It seems to be related to the allocation size somehow. I don't have much clue what the changes are for in above linked PR that broke the functionality for me, but just reporting this is happening. 34mb size seems to be enough to trigger this.

I'll use the previous versions meanwhile.

`main.rs:`
```rust
use vulkano::buffer::{BufferUsage, DeviceLocalBuffer};
use vulkano::device::{Device, DeviceExtensions};
use vulkano::instance::{Instance, InstanceExtensions, PhysicalDevice};

fn main() {
    // Add instance extensions based on needs
    let instance_extensions = InstanceExtensions {
        khr_surface: true,
        khr_xlib_surface: true,
        khr_get_physical_device_properties2: true,
        khr_get_surface_capabilities2: true,
        ..InstanceExtensions::none()
    };
    // Create instance
    let instance =
        Instance::new(None, &instance_extensions, None).expect("Failed to create instance");
    // Get most performant device (physical)
    let physical = PhysicalDevice::enumerate(&instance)
        .fold(None, |acc, val| {
            if acc.is_none() {
                Some(val)
            } else if acc.unwrap().limits().max_compute_shared_memory_size()
                >= val.limits().max_compute_shared_memory_size()
            {
                acc
            } else {
                Some(val)
            }
        })
        .expect("No physical device found");
    println!(
        "Using device: {} (type: {:?})",
        physical.name(),
        physical.ty()
    );
    let queue_family = physical
        .queue_families()
        .find(|&q| q.supports_graphics())
        .expect("couldn't find a graphical queue family");
    let device_extensions = DeviceExtensions::supported_by_device(physical);
    let features = physical.supported_features();
    // Needed extension for shared buffers
    assert!(device_extensions.khr_external_memory_fd);
    let (device, mut _queues) = {
        Device::new(
            physical,
            &features,
            &device_extensions,
            [(queue_family, 0.5)].iter().cloned(),
        )
        .expect("failed to create device")
    };

    let vk_buffer = unsafe {
        DeviceLocalBuffer::<[u8]>::raw_with_exportable_fd(
            device,
            34000000, // !ToDo: Try changing this value to see when 11: SIGSEGV happens
            BufferUsage::all(),
            Vec::new(),
        )
        .expect("Failed to allocate device local buffer")
    };
    println!("{:#?}", vk_buffer);
}
```

**Comment by hakolao** [comment] 2021-04-09 14:03
cc @gurchetansingh, you might know about this having worked on the PR

**Comment by gurchetansingh** [comment] 2021-04-09 17:27
Can you simply your test app further?  

`DeviceMemoryBuilder::new(device.clone(), memory_type.id(), size).export_info(handle_type).build()?;`

could also exhibit the problem

**Comment by hakolao** [comment] 2021-04-12 16:29
I'll try to get a moment to debug further soon!

**Comment by gurchetansingh** [comment] 2021-04-12 17:27
Thank you @hakolao!  This is mostly like pointer thrashing.  

`gdb --args ./your_app`
`break ptr_chain_iter`

could be chance to improve ur gdb skills.

**Comment by hakolao** [comment] 2021-04-13 14:00
Findings with clion's debugger:

I've not been quite able to get segfault with just the `DeviceMemoryBuilder` (yet), but some findings when debugging:

Finding 1:
- In the example of above `main.rs` at the `MemoryBuilder` stage of the allocation
- `self.allocate.pNext` is NULL, thus I'd assume that the `ptr_chain_iter` should return an empty iterator, but it does not seem to convert the incoming reference `ptr` to NULL before scan. (Might have understood this one wrong))
- And if it's null the `.unwrap` on the chain last should fail... but does not, as it is not null. Anyway, I don't think the `pNext` should be passed there directly. Instead we should pass incoming `next` like Ash does see [Ash](https://github.com/MaikKlein/ash/blob/5bc52dcd0a707340275733a0c89261176be32053/generator/src/lib.rs) and set .pNext to be next_ptr where its next becomes the NULL.

Finding 2:
- I noticed that inside `push_next` after getting the first `last_next`, its `s_type` becomes `self.allocate.allocationSize`.  (when ever the segfault does not happen, and it does not happen at smaller allocation, though no idea why, but I don't think stuff work nevertheless). Likely `BaseOutStructure` should have `#[repr(C)]` or something to ensure field order. Ash too has repr c.

`push_next` is different from the ash version, and at least in my use case doesn't seem to work right. But none of my fix attempts also work, so I've not been able to fix this. What I've tried:

- Push next more like ash:
```
    fn push_next<T: ExtendsMemoryAllocateInfo>(mut self, next: &mut T) -> DeviceMemoryBuilder<'a> {
        unsafe {
            let next_ptr = next as *mut T as *mut BaseOutStructure;
            let last_next = ptr_chain_iter(next).last().unwrap();
            (*last_next).p_next = self.allocate.pNext as _;
            self.allocate.pNext = next_ptr as _;
        }

        self
    }
```

- `#[repr(C)]` on `BaseOutStructure`
- Setting `pNext` on the builder if it's NULL.
- Deref `p_ptr` in `ptr_chain_iter`: `if (*p_ptr).is_null()`
- All at once, one at a time, various combinations of above

I think that as we reinterpret the `BaseStructure` inside `ptr_chain_iter` we should then get a ref to the p next and so on, but this is the part that segfaults and as the implementation differs a bit from `ash` I'd think this is where a fix would be in place (or `push_next`. But have not been able to come up with one.

Also, it would be nice to copy paste the comments from ash when `shamelessly` copying internal functions from there :D

**Comment by hakolao** [comment] 2021-04-13 14:42
Might the pointers also get lost in the scope of the `push_next`. Previously the `pNext` was set from `self.export_info` directly

**Comment by hakolao** [comment] 2021-04-13 16:30
Our exported & cuda imported memory also worked with this fix :)

**Comment by dadleyy** [comment] 2021-04-16 21:25
hey all - I'm running into a segfault that I believe to be related to this issue on mac os. I've tried my best to whittle a reproduction down to the minimal amount of code [here](https://github.com/dadleyy/vulkano-seg-1545/blob/master/src/main.rs). 

I am running this against the latest master by using cargo's `[patch.crates-io]` override feature, using a local copy of this repo that is up to date with master, including the change from [`7db41e5`](https://github.com/vulkano-rs/vulkano/commit/7db41e530903351214056dfceefa58acbc8823aa).

the last bit of output before the segfault:

```
VUID-VkMemoryAllocateInfo-pNext-pNext(ERROR / SPEC): msgNum: -633955574 - Validation Error: [ VUID-VkMemoryAllocateInfo-pNext-pNext ] Object 0: handle = 0x7fcdac848418, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xda369b0a | vkAllocateMemory: pAllocateInfo->pNext chain includes a structure with unknown VkStructureType (-1409041408); Allowed structures are [VkDedicatedAllocationMemoryAllocateInfoNV, VkExportMemoryAllocateInfo, VkExportMemoryAllocateInfoNV, VkExportMemoryWin32HandleInfoKHR, VkExportMemoryWin32HandleInfoNV, VkImportAndroidHardwareBufferInfoANDROID, VkImportMemoryFdInfoKHR, VkImportMemoryHostPointerInfoEXT, VkImportMemoryWin32HandleInfoKHR, VkImportMemoryWin32HandleInfoNV, VkMemoryAllocateFlagsInfo, VkMemoryDedicatedAllocateInfo, VkMemoryOpaqueCaptureAddressAllocateInfo, VkMemoryPriorityAllocateInfoEXT]. This error is based on the Valid Usage documentation for version 170 of the Vulkan header.  It is possible that you are using a struct from a private extension or an extension that was added to a later version of the Vulkan header, in which case the use of pAllocateInfo->pNext is undefined and may not work correctly with validation enabled The Vulkan spec states: Each pNext member of any structure (including this one) in the pNext chain must be either NULL or a pointer to a valid instance of VkDedicatedAllocationMemoryAllocateInfoNV, VkExportMemoryAllocateInfo, VkExportMemoryAllocateInfoNV, VkExportMemoryWin32HandleInfoKHR, VkExportMemoryWin32HandleInfoNV, VkImportAndroidHardwareBufferInfoANDROID, VkImportMemoryFdInfoKHR, VkImportMemoryHostPointerInfoEXT, VkImportMemoryWin32HandleInfoKHR, VkImportMemoryWin32HandleInfoNV, VkMemoryAllocateFlagsInfo, VkMemoryDedicatedAllocateInfo, VkMemoryOpaqueCaptureAddressAllocateInfo, or VkMemoryPriorityAllocateInfoEXT (https://vulkan.lunarg.com/doc/view/1.2.170.0/mac/1.2-extensions/vkspec.html#VUID-VkMemoryAllocateInfo-pNext-pNext)
    Objects: 1
        [0] 0x7fcdac848418, type: 3, name: NULL
zsh: segmentation fault  cargo run --release
```

the only thing jumps out to me is the part about the `pType`:

```
vkAllocateMemory: pAllocateInfo->pNext chain includes a structure with unknown VkStructureType (-1409041408);
```

I do not have much experience debugging memory issues (including using `gdb`) yet, so I'm not sure what to look for. I also was pretty stumped when the `teapot` example on my local clone of this repo runs fine, since it is also using [`AttachmentImage::transient`](https://github.com/vulkano-rs/vulkano/blob/fb187e888469ac2255855ffa8b7022258a688222/examples/src/bin/teapot/main.rs#L319), which appears to be the call that causes the segfault. All this is to say that I don't have much confidence there even is an issue here, or if this is somehow isolated to my machine. I believe that cloning the repo linked above from another machine would help answer that quickly. I can see if I can find one to use in the meantime.

| | |
| --- | --- |
| os | macos v10.15.7 |
| `cargo --version` | cargo 1.51.0 (43b129a20 2021-03-16) |

If there is anything I can do to help or more information I can provide, I would be happy to help. I really appreciate all the work going into this project.

**Comment by gurchetansingh** [comment] 2021-04-16 21:29
Did you try top of tree with the fix?

https://github.com/vulkano-rs/vulkano/pull/1554

**Comment by dadleyy** [comment] 2021-04-16 21:40
I could've sworn I was. I've changed the override to use a `git` resolution:

```
[patch.crates-io]
vulkano = { git = 'https://github.com/vulkano-rs/vulkano', rev = 'fb187e888469ac2255855ffa8b7022258a688222' }
```

instead of using `{ path = '...' }`. now I'm only seeing the segfault when running with `--release` (`cargo run --release`).

**Comment by gurchetansingh** [comment] 2021-04-22 22:57
@dadleyy I tried `vulkano-seg-1545`, but did not have any segmentation fault.M

smithay_client_toolkit::window::concept_frame] No font could be found

Maybe it's an architecture specific issue?  Also I changed this for it to compile:

 [dependencies]
-vulkano = { version = "0.22" }
-vulkano-win = { version = "0.22" }
+vulkano = { path = "../vulkano/vulkano" }
+vulkano-win = { path = "../vulkano/vulkano-win" }
 winit = { version = "0.24.0" }
 env_logger = { version = "0.8.3" }
 log = { version = "^0.4.1" }
-
-[patch.crates-io]
-vulkano = { git = 'https://github.com/vulkano-rs/vulkano', rev = 'fb187e888469ac2255855ffa8b7022258a688222' }

**Comment by dadleyy** [comment] 2021-05-07 14:45
@gurchetansingh what architecture/environment are you running on? I was only experiencing this when running `--release` builds, did you try that?

> smithay_client_toolkit::window::concept_frame] No font could be found

I'm confused - did you mean to include this in your comment? was that output from running [vulkano-seg-1545](https://github.com/dadleyy/vulkano-seg-1545)?

----

I'm still experiencing this issue, but I have beens slowly poking away at what I might think is the issue. I just finished implementing some changes that appear to fix this issue [on this branch of my fork](https://github.com/vulkano-rs/vulkano/compare/master...dadleyy:no-chain?expand=1), though I'm not 100% certain why it would be a solution.

I'm thinking this has to do with the memory pointed to when using the `push_next` + `ptr_chain_iter` being invalidated somehow - which explains why the `sType` ends up as garbage like `-1409041408`: if we `push_next(&mut T)` and then the location of `T` changes at some point, the `pNext` pointer on our `MemoryAllocateInfo` would be invalid right?

I'm definitely still learning rust so this is all just me spitballing.

**Comment by hakolao** [comment] 2021-05-13 09:38
I also attempted this with the `--release` just now, and it segfaulted :S. Looks like the fix wasn't enough indeed.

Works without --release.

**Comment by hakolao** [comment] 2021-05-13 11:07
A better fix attempt... #1580. Hopefully this would fix it once and for all. Rust can sometimes make ptr play so hard...

**Comment by pwaller** [comment] 2021-12-19 16:36
I'm seeing this on head today, except with `AttachmentImage::new_with_exportable_fd` -- and again, it crashes with a `--release` build but not a debug build.

**Comment by pwaller** [comment] 2021-12-19 16:48
The above issue I think is caused by this, and separate to the original issue as reported, sorry: https://github.com/vulkano-rs/vulkano/pull/1734/files#r771974391

**Comment by Rua** [comment] 2022-05-14 13:28
The dropped temporary is fixed now, so if that was the problem here, it should be fixed too. I'll reopen if it's still present.

**Closed by Rua** 2022-05-14 13:28 UTC
Labels: type: bug
