### ISSUE TITLE
Initialization procedure of StorageImage seems incorrect

### ISSUE THREAD

**Issue by HadrienG2** [vulkano-rs/vulkano#974] opened 2018-06-11 19:52 UTC
My Vulkan validation layer told me that there's something wrong with image layouts in [the first example of the "Using images" section of the Vulkano guide](http://vulkano.rs/guide/image-export). It chokes when the command buffer is submitted to the device, even when it contains only a clear command, with the message:

    ERROR @ DS => Object: 0x7f8c5fce6c00 | Cannot submit cmd buffer using image (0x11) [sub-resource: aspectMask 0x1 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_UNDEFINED when first use is VK_IMAGE_LAYOUT_GENERAL.

So I went to investigate a bit. Here is what I found:

- A StorageImage is, as far as I can tell, always created in the Undefined layout:
    * [StorageImage::new()](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/image/storage.rs#L74) is a thin wrapper around [StorageImage::with_usage()](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/image/storage.rs#L102)
    * StorageImage::with_usage() calls [UnsafeImage::new()](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/image/sys.rs#L82) with its preinitialized_layout parameter set to false.
    * In this configuration, [UnsafeImage::new() creates images in the Undefined layout](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/image/sys.rs#L485).
    * No layout transition is subsequently performed by the UnsafeImage and StorageImage constructors.
- The [vkClearColorImage()](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#clears-outside) API requires images to be initially in the General or TransferDstOptimal layout, so clearly a layout transition will need to be performed at the beginning of the command buffer that calls this command.
- [AutoCommandBufferBuilder::clear_color_image()](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/auto.rs#L747) is a thin wrapper around [AutoCommandBufferBuilder::clear_color_image_dimensions()](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/auto.rs#L763).
- After some validation, AutoCommandBuffeBuilder::clear_color_image_dimensions() calls the inner [SyncCommandBufferBuilder::clear_color_image()](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/synced/commands.rs#L569), requesting a TransferDstOptimal image layout.
- SyncCommandBufferBuilder::clear_color_image() dispatches, in turn, to [SyncCommandBufferBuilder::append_command()](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/synced/base.rs#L426) and [SyncCommandBufferBuilder::prev_cmd_resource()](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/synced/base.rs#L464), following the usual pattern of this builder. The first method stores the "raw" command object, the second method is of higher interest to us here as it handles resource-related pipeline barriers, including image layout transitions.
- SyncCommandBufferBuilder::prev_cmd_resource(), in turn, [does have a path for handling the case where images are initially in the wrong layout](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/synced/base.rs#L622). We're getting close!
- On that code path, [it is assumed that img.initial_layout_requirement() tells the truth about the initial state of the image](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/command_buffer/synced/base.rs#L652)...
- But that is wrong in our case, since [StorageImage always reports its initial layout to be General](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/image/storage.rs#L191), even when it is still in the Undefined state! Therefore, the initial pipeline barrier starts from the General state instead of starting from the Undefined state, which is why my validation layer is complaining.

At this point, my head feels a bit dizzy from all the layers of abstraction that I've just been through, but I think I have found where the inconsistency is. I can think of at least three ways of fixing this:

- The StorageImage constructor could silently initialize every image. But that is very invasive and unexpected (as it requires silently submitting command buffers to a device queue under the hood), so I do not expect this option to be considered.
- SyncCommandBufferBuilder::prev_cmd_resource() could special-case newly created images and create a different kind of layout transition barrier for them.
- StorageImage::initial_layout_requirement() could return something different when an image has just been created.

What should it be?

**Comment by HadrienG2** [comment] 2018-06-11 20:07
As an ugly workaround, one can use the unsafe [ImageAccess::forced_undefined_initial_layout()](https://docs.rs/vulkano/0.7/vulkano/image/traits/trait.ImageAccess.html#method.forced_undefined_initial_layout) method to wrap the StorageImage into something which always reports its initial layout to be Undefined. That's obviously not great, but for this simple example it does the job.

**Comment by HadrienG2** [comment] 2018-06-12 19:34
...it doesn't work with the next example, though, mumbling something about a missing SafeDeref trait. All the more motivation for investigating the proper solution I guess :)

**Comment by HadrienG2** [comment] 2018-06-13 18:41
ImmutableImage shows [one way this can be done](https://github.com/vulkano-rs/vulkano/blob/master/vulkano/src/image/immutable.rs#L115): the "uninitialized" constructor returns both the image object and a proxy initializer object which must be used first before the image is usable.

Perhaps this solution could be generalized to other image types?

**Comment by realitix** [comment] 2018-06-21 08:35
Thanks @HadrienG2, for your investigation.
I have a similar problem with image layout (swapchain) #977 .
I will follow your code path to find a workaround.
@tomaka seems busy ! :wink:

**Comment by tomaka** [comment] 2018-07-08 07:49
> @tomaka seems busy ! wink

It's not so much that I'm busy enough to not have time at all.
The problem is more that I agree with you that this whole access checking system is really obscure and difficult to understand and debug, even for myself.
I have the intuition that some fixes should be made at a deeper level.

**Comment by knappador** [comment] 2019-03-17 18:05
I'd like to get assigned on this since it's related to code I'm reading now.  @tomaka or org access?  :dancing_women:

**Comment by rukai** [comment] 2019-03-18 07:49
Sure feel free to work on it.

**Comment by knappador** [comment] 2019-04-15 17:56
I keep coming back to layout transitions as a ripe candidate to impose some typestates on so that we don't have to chase this stuff up and down the layers all the time.  Re-reading this thread reinforces this perception.  The name layout transitions sounds a whole lot like all of the behavior can be summed up with just one valid FSM, but I just haven't read the docs deep enough yet.

**Comment by mitchmindtree** [comment] 2019-04-23 06:11
@freesig has [a patch](https://github.com/mitchmindtree/vulkano/pull/6) that seems to fix this. We're just doing some testing as after applying the patch I'm seeing some odd text distortion issues downstream, but its seeming more likely that's just a mesa intel driver bug. After applying his patch we're seeing no more image layout transition validation layers whatsoever when running it on our ~100 examples at the nannou repo, many which contain significantly different layout transition graphs.

@knappador yes an option for stronger types could be nice to check the transitions at compile time. That said rust's type system is very limited in terms of what it can provide an easy-to-use API around that also compiles in a reasonable amount of time, especially for complicated state machine graphs like we have here. The issue can be compared to checking the length of `Vec`s at runtime when indexing - in theory, everyone could be avoiding these run-time checks by using `typenum` to guarantee correct indices. The reality however is that the long compile-times and unwieldy, complicated types make it not worth the trade-off. Perhaps if rust had a dependent type system these sorts of checks would be a lot easier and user-friendly, but it looks like any chance of that is a long way into the future.

Another issue to consider with creating a completely type-safe option is that often developers creating higher-level abstractions around these image types can't always know exactly what the layout will be at compile time. For example, this would be the case any time a user might want to be able to re-arrange the way images are used in the render graph at run-time. As a result, we would likely need some way to allow for moving the checks to run-time anyway (which is kind of what vulkano is already trying to do, it has just been missing a lot of them).

Anyway, I don't mean to discourage the idea, I think its worth exploring and I'd love to see what you come up with! I just thought these points would be worth considering before diving in.

**Comment by knappador** [comment] 2019-04-23 15:04
@mitchmindtree  I'm still [researching](https://github.com/vulkano-rs/vulkano/issues/1193) the available tools and beginning to look at the assembly chonked out, but in general, the function implementations are not parametric (still should compile fast to a small program) and the type information doesn't need to leak up to the user.

I was unaware that `typenum` existed and I absolutely hate the API but now I'll go read the source and figure out what tricks they've gotten figured out :cat:

**Comment by knappador** [comment] 2019-04-24 18:14
I've muted this issue and am going to press ahead with a lower level Vulkan binding on E-Nguyen for a bit to get on a healthier track.  I've had some synchronization issues that are drop dead simple in raw Vulkan but seem to be missing implementation or behavior in Vulkano, and the direction of E-Nguyen will end up strongly favoring developing it's own thinner abstractions around independent off-screen renders.

Will be prioritizing more DBC and less runtime checks while "lying" about safety for now due to the fact that no use of Vulkan can eliminate undefined behavior without a complete abstraction around all behavior behind the call, requiring proof or tracking of all related downstream state.  Such proof or complete state tracking,  whether completely actually achievable or not, will be built on top of complete abstractions at the lowest level for at least limited dimensions of calls.

I'm maintaining PR's to landing and then jetting

**Comment by AustinJ235** [comment] 2019-11-26 07:13
Fixed in https://github.com/vulkano-rs/vulkano/pull/1171

**Closed** 2019-11-26 07:12 UTC
